version: '3.8'

services:
  aedp-portal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aedp-portal
    restart: unless-stopped
    ports:
      - "7177:7177"
    environment:
      - NODE_ENV=production
